services:
  traefik:
    image: traefik:v3.1
    command:
      - '--log.level=DEBUG'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=mohitdolani19@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - 'letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    deploy:
      resources:
        limits: { cpus: '0.2', memory: '200M' }
        reservations: { cpus: '0.1', memory: '75M' }

  web:
    image: ghcr.io/ankit-kumar-jat/alogstream:${GIT_COMMIT_HASH:-latest}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
      - 'traefik.http.routers.web.rule=Host(`${HOST}`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls.certresolver=myresolver'
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - HONEYPOT_SECRET=${HONEYPOT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
    deploy:
      update_config:
        order: start-first

  # following is used to cleanup unused docker images and containers as it can fill up storage very fast
  swarm-cleanup:
    image: docker
    command: |
      sh -c "
        docker container prune -f &&
        docker image prune -f -a"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        delay: 24h
      resources:
        limits: { cpus: '0.1', memory: '32M' }
        reservations: { cpus: '0.025', memory: '16M' }

volumes:
  letsencrypt:
